### PR TITLE
Make sure we handle non-errors

### PR DESCRIPTION
**Pull request by jesushernandez**
At the moment, if a subscriber panics with eg: `panic("foo")`, it'll bring the whole service down (when the subscriber is part of a service), since the recover middleware will panic here https://github.com/lileio/pubsub/blob/master/middleware/recover/recover.go#L46 (invalid interface conversion)

### CODE REVIEW

**Review by arbarlow — APPROVED** [review]

**Comment by arbarlow** [comment]
Thanks! Merged

**Comment by jesushernandez** [comment]
@arbarlow cheers! Should we create a new tag? To avoid those autogenerated version hashes when doing @latest

**Comment by arbarlow** [comment]
Sure

**Comment by arbarlow** [comment]
v2.6.0 now minted

**Pull request merged**
