### PR TITLE
Update opentracing & openzipkin w/ contrib repo

### PR DESCRIPTION
**Pull request by oz**
This updates both dependencies:

1. for opentracing, it allows us to use the recent-ish mock structs in tests.
2. for openzipkin, this switches to the contrib repository, as the old one is no longer used.

I wish I could make 2 PRs, but the two are kind of intertwined right now.

Hope this helps!

### CODE REVIEW

**Comment by arbarlow** [comment]
Really sorry I didn't see this @oz, CI is failing but I'll sort that today and we'll get this merged

**Comment by arbarlow** [comment]
hi @oz, this is ready,. but I'll need you to resolve some conflicts first?

**Comment by oz** [comment]
I rebased the PR on top of master.

Hope this helps!

**Comment by jesushernandez** [comment]
@oz Hey, I was about to do exactly what you're doing here. Do you mind rebasing again (sorry)? I'll make sure it's merged promptly this time 👍

**Comment by oz** [comment]
I just got the notification, was offline for a good while.

Thanks for merging that. :+1:

**Pull request closed without merging**
